### ISSUE TITLE
XSS in submit form

### ISSUE THREAD

**Issue by g4s8** [skapral/poetryclub#6]
User can submit escaped javascript into the "post submit" form. E.g. this script
```
 javascript:/*--></title></style></textarea></script></xmp><svg/onload='+/"/+/onmouseover=1/+/[*/[]/+alert(1)//'>
```
will show alert with "1" text, most probably reviewer's browser also executes this script.

Form inputs should be escaped to avoid this kind of atacks.

**Comment by skapral** [comment]
@g4s8 I recently realized that I messed up the deployment, when tuned things up - left old pre-release version deployed. The XSS issue you saw has been fixed already in version 0.0.0 - see [here](https://github.com/skapral/poetryclub/blob/master/poetryclub-service/src/main/java/com/github/skapral/poetryclub/service/jersey/PoetryEndpoint.java#L103). `ScalarUrl` there won't let non-URL input to pass through, causing exception.

There are however the other places which can be hacked the same way. For example, the form for creating new community is now vulnerable. I'll fix this in scope of this issue. I also deployed version 0.0.0 so that currently it shouldn't be possible to provide non-URL contributions and feedbacks.
